project_id = "zldawmyoscicxoiqvfpu"

[api]
enabled = true
port = 54321
schemas = ["public", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[auth]
enabled = true
port = 54324
site_url = "http://localhost:3000"
additional_redirect_urls = ["https://zldawmyoscicxoiqvfpu.supabase.co"]
jwt_expiry = 3600
enable_signup = false
enable_anonymous_signups = true

[db]
port = 54322
shadow_port = 54320
major_version = 15

[edge_functions]
enabled = true
port = 54323

[functions.approve-owner-request]
verify_jwt = false

[functions.send-booking-notification]
verify_jwt = false

[functions.verify-owner-otp]
verify_jwt = false

[functions.create-field]
verify_jwt = true

[functions.test-webhook]
verify_jwt = false

[functions.test-webhook-simple]
verify_jwt = false

[functions.force-confirm-booking]
verify_jwt = false

[functions.cinetpay-webhook]
verify_jwt = false

[realtime]
enabled = true
port = 54325

[storage]
enabled = true
port = 54326
file_size_limit = "50MiB"

[analytics]
enabled = false
port = 54327
vector_port = 54328

[inbound_mail]
enabled = false
port = 54329

[pooler]
enabled = false
port = 54330
pool_mode = "transaction"
default_pool_size = 20
max_client_conn = 100

[experimental]
orioledb_version = ""
s3_host = "env(SUPABASE_S3_HOST)"
s3_region = "env(SUPABASE_S3_REGION)"
s3_access_key_id = "env(SUPABASE_S3_ACCESS_KEY_ID)"
s3_secret_access_key = "env(SUPABASE_S3_SECRET_ACCESS_KEY)"