project_id = "zldawmyoscicxoiqvfpu"

[api]
enabled = true
port = 54321
schemas = ["public", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[auth]
enabled = true
site_url = "http://localhost:3000"
additional_redirect_urls = ["https://zldawmyoscicxoiqvfpu.supabase.co"]
jwt_expiry = 3600
enable_signup = false

[db]
port = 54322
shadow_port = 54320
major_version = 15


[functions.approve-owner-request]
verify_jwt = false

[functions.send-booking-notification]
verify_jwt = false

[functions.verify-owner-otp]
verify_jwt = false

[functions.create-field]
verify_jwt = true

[functions.test-webhook]
verify_jwt = false

[functions.test-webhook-simple]
verify_jwt = false

[functions.force-confirm-booking]
verify_jwt = false

[functions.cinetpay-webhook]
verify_jwt = false

[functions.create-owner-payout]
verify_jwt = false

[functions.create-owner-contact]
verify_jwt = false

[realtime]
enabled = true

[storage]
enabled = true
file_size_limit = "50MiB"

[analytics]
enabled = false
port = 54327
vector_port = 54328


[experimental]
orioledb_version = ""