project_id = "zldawmyoscicxoiqvfpu"

[api]
enabled = true
port = 54321
schemas = ["public", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[auth]
enabled = true
site_url = "http://localhost:3000"
additional_redirect_urls = ["https://zldawmyoscicxoiqvfpu.supabase.co"]
jwt_expiry = 3600
enable_signup = false

[db]
port = 54322
shadow_port = 54320
major_version = 15

# FONCTIONS ACTIVES POUR LE SYSTÈME MYSPORT

[functions.approve-owner-request]
verify_jwt = false

[functions.create-field]
verify_jwt = true

[functions.cinetpay-webhook]
verify_jwt = false

[functions.cinetpay-transfer-webhook]
verify_jwt = false

[functions.create-owner-payout]
verify_jwt = false

[functions.create-cinetpay-payment]
verify_jwt = false

[functions.create-cinetpay-merchant]
verify_jwt = false

[functions.approve-booking]
verify_jwt = false

[functions.confirm-booking-owner]
verify_jwt = false

[functions.send-booking-email]
verify_jwt = false

[functions.send-sms-notification]
verify_jwt = false

[functions.cleanup-expired-bookings]
verify_jwt = false

[functions.create-owner-contact]
verify_jwt = false

[functions.paydunya-ipn]
verify_jwt = false

[functions.create-paydunya-invoice]
verify_jwt = false

[functions.create-paydunya-payout]
verify_jwt = false

[realtime]
enabled = true

[storage]
enabled = true
file_size_limit = "50MiB"

[analytics]
enabled = false
port = 54327
vector_port = 54328

[experimental]
orioledb_version = ""